// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repo.Models;

public partial class Notification
{
    public int NotificationId { get; set; }

    public int? CustomerId { get; set; }

    public string Title { get; set; }

    public string Body { get; set; }

    public string Type { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? ReadAt { get; set; }

    public string Status { get; set; }

    public byte? Priority { get; set; }

    public DateTime? ScheduledAt { get; set; }

    public virtual Customer Customer { get; set; }
}