// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repo.Models;

public partial class Payment
{
    public int Id { get; set; }

    public int? SubscriptionId { get; set; }

    public decimal Amount { get; set; }

    public string Method { get; set; }

    public DateTime? PaidAt { get; set; }

    public string Status { get; set; }

    public virtual Subscription Subscription { get; set; }
}