// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repo.Models;

public partial class Product
{
    public int ProductId { get; set; }

    public int? CategoryId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public decimal Price { get; set; }

    public string ImageUrl { get; set; }

    public string ImageId { get; set; }

    public virtual Category Category { get; set; }

    public virtual ICollection<Redemption> Redemptions { get; set; } = new List<Redemption>();

    public virtual ICollection<Subscription> Subscriptions { get; set; } = new List<Subscription>();
}