// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repo.Models;

public partial class Redemption
{
    public int RedemptionId { get; set; }

    public int? SubscriptionId { get; set; }

    public int? StoreId { get; set; }

    public int? StaffId { get; set; }

    public int? ProductId { get; set; }

    public int? Quantity { get; set; }

    public DateTime? RedeemedAt { get; set; }

    public virtual Product Product { get; set; }

    public virtual Staff Staff { get; set; }

    public virtual Store Store { get; set; }

    public virtual Subscription Subscription { get; set; }
}