// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repo.Models;

public partial class Staff
{
    public int StaffId { get; set; }

    public int? StoreId { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string Role { get; set; }

    public string Password { get; set; }

    public virtual ICollection<Redemption> Redemptions { get; set; } = new List<Redemption>();

    public virtual Store Store { get; set; }
}