// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repo.Models;

public partial class Store
{
    public int StoreId { get; set; }

    public string Name { get; set; }

    public string Address { get; set; }

    public string Phone { get; set; }

    public bool? Active { get; set; }

    public virtual ICollection<Redemption> Redemptions { get; set; } = new List<Redemption>();

    public virtual ICollection<Staff> Staff { get; set; } = new List<Staff>();
}