// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repo.Models;

public partial class Subscription
{
    public int SubscriptionId { get; set; }

    public int? CustomerId { get; set; }

    public int? PlanId { get; set; }

    public int? ProductId { get; set; }

    public DateOnly? StartDate { get; set; }

    public DateOnly? EndDate { get; set; }

    public int? RemainingDays { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string Status { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual SubscriptionPlan Plan { get; set; }

    public virtual Product Product { get; set; }

    public virtual ICollection<Redemption> Redemptions { get; set; } = new List<Redemption>();
}